name: Create Issue

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the issue'
        required: true
      body:
        description: 'Body of the issue'
        required: false

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v6
        with:
          script: |
            const title = '${{ github.event.inputs.title }}';
            const body = '${{ github.event.inputs.body || '' }}';

            const { data: issue } = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body
            });

            console.log(`Issue created: ${issue.html_url}`);
