name: Create Issue

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the issue'
        required: true
      body:
        description: 'Body of the issue'
        required: false

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: ${{ github.event.inputs.title }}
          body: ${{ github.event.inputs.body }}
